### ISSUE TITLE
Incorrect Content-Type for JSON response 

### ISSUE THREAD

**Issue by TheJaysH** [EvilInsultGenerator/website#15]
Hi,

When returning JSON response the content-type is not being returned as `application/json` 

![image](https://user-images.githubusercontent.com/14791907/100545573-5cc52e00-3254-11eb-8920-f36ed5888db7.png)

**Comment by EvilInsultGenerator** [comment]
Thanks for noticing it. 
I will check it. Can you please have a look too, @Schokobecher?
@TheJaysH, would you be up for a fixing PR?

**Comment by TheJaysH** [comment]
Sure bud, I'll fork, fix and PR when kids gone bed 👍

**Comment by TheJaysH** [comment]
#16 PR Submitted
